- hosts: qld_ref_nfs
  become: true
  vars_files:
   - group_vars/all.yml
   - group_vars/VAULT
  vars:
  - nfs_exports:
    #- "/mnt/vdb/alphafold_db {{ hostvars['pulsar-qld-gpu1'].ansible_ssh_host.split('.')[:-1] | join('.') }}.0/32(rw,async,no_root_squash,no_subtree_check)"
    #- "/mnt/vdb/alphafold_db {{ hostvars['pulsar-qld-gpu2'].ansible_ssh_host.split('.')[:-1] | join('.') }}.0/32(rw,async,no_root_squash,no_subtree_check)"
    # the QRIScloud Nectar CIDR applies to ALL Qld Nectar VMs
    - "/mnt/vdb/alphafold_db 203.101.224.0/20(rw,async,no_root_squash,no_subtree_check)"
  roles:
    - common
    - geerlingguy.nfs
  post_tasks:
    - name: Reload exportfs
      command: exportfs -ra
